### ISSUE TITLE
payment Method versus payment Instruments

### ISSUE THREAD

**Issue by cyberphone** [rsolomakhin/secure-payment-confirmation#33] opened 2020-10-23 06:40 UTC
From the samples it appears that there is just a payment method and no payment instruments.

If this is correct, the universality of this system will be unnecessary limited.

**Comment by ianbjacobs** [comment] 2020-10-26 12:27
Payment instruments are being addressed separately.

**Comment by ianbjacobs** [comment] 2020-10-26 13:08
Closing because instrument storage is not addressed in this version of SPC (by design)

**Closed by ianbjacobs** 2020-10-26 13:08 UTC

**Comment by cyberphone** [comment] 2021-02-17 19:02
https://github.com/w3c/webauthn/issues/1570#issuecomment-780611040 shows how this could be done
